In [2]:
from googlemaps import places
import urllib
import pandas as pd
from bs4 import BeautifulSoup

In [3]:
df=pd.read_csv("unicourse.csv")
df

,University name,course Url,Latitude,Longitude,Address
0,Massachusetts Institute of Technology (MIT),https://engineering.mit.edu/,42.360091,-71.094160,"77 Massachusetts Ave, Cambridge, MA 02139, USA"
1,Stanford University,https://www.stanford.edu/academics/,37.427475,-122.169719,"450 Serra Mall, Stanford, CA 94305, USA"
2,Harvard University,https://www.harvard.edu/,42.377003,-71.116660,"Cambridge, MA 02138, USA"
3,California Institute of Technology (Caltech),http://www.cms.caltech.edu/academics/grad_cms,34.137658,-118.125269,"1200 E California Blvd, Pasadena, CA 91125, USA"
4,University of Cambridge,https://www.graduate.study.cam.ac.uk/internati...,52.204267,0.114908,"The Old Schools, Trinity Ln, Cambridge CB2 1TN..."
5,University of Oxford,http://www.ox.ac.uk/,51.754816,-1.254367,"Oxford OX1 2JD, UK"
6,UCL (University College London),https://www.ucl.ac.uk/,51.524559,-0.134040,"Gower St, Bloomsbury, London WC1E 6BT, UK"
7,Imperial College London,https://www.imperial.ac.uk/engineering/,51.498800,-0.174877,"Kensington, London SW7 2AZ, UK"
8,University of Chicago,http://collegeadmissions.uchicago.edu/?,41.788608,-87.598713,"5801 S Ellis Ave, Chicago, IL 60637, USA"
9,ETH Zurich - Swiss Federal Institute of Techno...,https://www.ethz.ch/en.html,47.376313,8.547670,"Rämistrasse 101, 8092 Zürich, Switzerland"
10,"Nanyang Technological University, Singapore (NTU)",http://www.ntu.edu.sg/,1.348310,103.683135,"50 Nanyang Ave, Singapore 639798"
11,Ecole Polytechnique Fédérale de Lausanne (EPFL),https://www.phdportal.com/universities/428/eco...,46.519056,6.566758,"Route Cantonale, 1015 Lausanne, Switzerland"
12,Cornell University,http://www.cornell.edu/academics/colleges.cfm,42.453449,-76.473503,"Ithaca, NY 14850, USA"
13,National University of Singapore (NUS),http://www.nus.edu.sg/,1.296643,103.776394,"21 Lower Kent Ridge Rd, Singapore 119077"
14,Yale University,https://www.yale.edu/academics/graduate-profes...,41.316324,-72.922343,"New Haven, CT 06520, USA"
15,Johns Hopkins University,http://anthropology.jhu.edu/,39.329901,-76.620518,"Baltimore, MD 21218, USA"
16,Columbia University,http://www8.gsb.columbia.edu/programs/mba,40.807536,-73.962573,"116th St & Broadway, New York, NY 10027, USA"
17,University of Pennsylvania,https://www.upenn.edu/researchdir,39.952219,-75.193214,"Philadelphia, PA 19104, USA"
18,The Australian National University,http://www.anu.edu.au/,-35.277700,149.118527,"Canberra ACT 0200, Australia"
19,University of Michigan,https://pharmacy.umich.edu/,42.278044,-83.738224,"500 S State St, Ann Arbor, MI 48109, USA"
20,Duke University,https://www.duke.edu/,36.001426,-78.938229,"Durham, NC 27708, USA"
21,The University of Edinburgh,https://www.ed.ac.uk/studying,55.944516,-3.189241,"Old College, South Bridge, Edinburgh EH8 9YL, UK"
22,King's College London,https://www.kcl.ac.uk/study/learningteaching/c...,51.511486,-0.115997,"Strand, London WC2R 2LS, UK"
23,Tsinghua University,http://www.tsinghua.edu.cn/publish/newthuen/,39.999667,116.326444,"30 Shuangqing Rd, Haidian Qu, Beijing Shi, China"
24,The University of Hong Kong,https://www.timeshighereducation.com/world-uni...,22.282999,114.137085,"Pok Fu Lam, Hong Kong"
25,"University of California, Berkeley (UCB)",https://www.berkeley.edu/,37.871899,-122.258540,"Berkeley, CA, USA"
26,The University of Tokyo,https://misk.org.sa/fellowship/services/the-un...,35.712678,139.761989,"7 Chome-3-1 Hongo, Bunkyō, Tokyo 113-8654, Japan"
27,Northwestern University,https://www.northwestern.edu/,42.056459,-87.675267,"633 Clark St, Evanston, IL 60208, USA"
28,The Hong Kong University of Science and Techno...,https://www.edx.org/school/hkustx,22.336400,114.265466,"Clear Water Bay, Hong Kong"
29,University of Toronto,https://www.utoronto.ca/,43.662892,-79.395656,"27 King's College Cir, Toronto, ON M5S 3H7, Ca..."
...,...,...,...,...,...
69,KU Leuven,https://www.kuleuven.be/english/research/phd,50.877954,4.700295,"Oude Markt 13, 3000 Leuven, Belgium"
70,Pohang University of Science And Technology (P...,http://admission.postech.ac.kr/linkUsen.do?f=s...,36.013886,129.323184,"77 Cheongam-ro, Jigok-dong, Nam-gu, Pohang, Gy..."
71,University of Copenhagen,http://www.ku.dk/english/,55.680230,12.572410,"Nørregade 10, 1165 København, Denmark"
72,University of Zurich,http://www.uzh.ch/en.html,47.374322,8.550981,"Rämistrasse 71, 8006 Zürich, Switzerland"
73,Universidad de Buenos Aires (UBA),http://www.uba.ar/,-34.593629,-58.483682,"Buenos Aires, Argentina"
74,National Taiwan University (NTU),http://nturanking.lis.ntu.edu.tw/Default.aspx,25.017340,121.539752,"No. 1, Section 4, Roosevelt Rd, Da’an District..."
75,Tohoku University,http://www.tohoku.ac.jp/en/,38.253834,140.874074,"2 Chome-1-1 Katahira, Aoba Ward, Sendai, Miyag..."
76,Durham University,https://www.dur.ac.uk/study/pg/,54.764986,-1.578203,"Durham DH1, UK"
77,Lund University,https://www.lunduniversity.lu.se/international...,55.711948,13.203493,"Lund, Sweden"
78,"University of North Carolina, Chapel Hill",https://www.unc.edu/,35.904912,-79.046913,"Chapel Hill, NC, USA"
79,Boston University,http://www.bu.edu/,42.350500,-71.105399,"Boston, MA 02215, USA"
80,The University of Sheffield,https://www.sheffield.ac.uk/international,53.380941,-1.487947,"Western Bank, Sheffield S10 2TN, UK"
81,The University of Auckland,https://www.auckland.ac.nz/en/on-campus/accomm...,-36.852338,174.769107,"Auckland 1010, New Zealand"
82,University of Birmingham,https://www.birmingham.ac.uk/International/ind...,52.450817,-1.930513,"Birmingham B15 2TT, UK"
83,University of Nottingham,https://www.nottingham.ac.uk/Utilities/a-z.aspx,52.938636,-1.195158,"Nottingham NG7 2RD, UK"
84,The Ohio State University,https://www.osu.edu/,40.014191,-83.030914,"Columbus, OH 43210, USA"
85,Zhejiang University,http://iczu.zju.edu.cn/english/redir.php?catal...,30.263944,120.123279,"38 Zheda Rd, Xihu Qu, Hangzhou Shi, Zhejiang S..."
86,"Trinity College Dublin, The University of Dublin",https://www.tcd.ie/business/msc/intl-management/,53.343794,-6.254572,"College Green, Dublin 2, Co. Dublin, Ireland"
87,Rice University,http://www.rice.edu/,29.717394,-95.401831,"6100 Main St, Houston, TX 77005, USA"
88,Korea University,https://graduate2.korea.ac.kr/,37.590799,127.027777,"145 Anam-ro, Anam-dong, Seongbuk-gu, Seoul, So..."
89,University of Alberta,https://www.ualberta.ca/law/,53.523219,-113.526319,"116 St & 85 Ave, Edmonton, AB T6G 2R3, Canada"
90,University of St Andrews,https://www.st-andrews.ac.uk/business-services...,56.341693,-2.792752,"St Andrews KY16 9AJ, UK"
91,Pennsylvania State University,http://www.psu.edu/,40.798213,-77.859908,"Old Main, State College, PA 16801, USA"
92,The University of Western Australia,http://uwa.edu.au/contact,-31.981179,115.819910,"35 Stirling Hwy, Crawley WA 6009, Australia"
93,Lomonosov Moscow State University,https://www.msu.ru/en/intcoop/,55.703935,37.528670,"ul. Leninskiye Gory, 1, Moskva, Russia, 119991"
94,The Hong Kong Polytechnic University,https://www.polyu.edu.hk/engl/study/pg-researc...,22.302847,114.178419,"11 Yuk Choi Rd, Hung Hom, Hong Kong"
95,University of Science and Technology of China,https://en.biox.ustc.edu.cn/,31.821994,117.280590,"1129 Huizhou Ave, Baohe Qu, Hefei Shi, Anhui S..."
96,KTH Royal Institute of Technology,https://www.kth.se/en,59.349806,18.070665,"Brinellvägen 8, 114 28 Stockholm, Sweden"
97,University of Geneva,http://www.unige.ch/droit/transnational/vie.html,46.199444,6.145116,"1205 Geneva, Switzerland"
98,Washington University in St. Louis,https://economics.wustl.edu/,38.648789,-90.310796,"1 Brookings Dr, St. Louis, MO 63130, USA"

In [5]:
df["Latitude"]=df.Latitude.astype(str)
df["Longitude"]=df.Longitude.astype(str)
df["latlong"]=df.Latitude+","+df.Longitude

In [6]:
df.head()

,University name,course Url,Latitude,Longitude,Address,latlong
0,Massachusetts Institute of Technology (MIT),https://engineering.mit.edu/,42.360091,-71.09416,"77 Massachusetts Ave, Cambridge, MA 02139, USA","42.360091,-71.09416"
1,Stanford University,https://www.stanford.edu/academics/,37.4274745,-122.169719,"450 Serra Mall, Stanford, CA 94305, USA","37.4274745,-122.169719"
2,Harvard University,https://www.harvard.edu/,42.3770029,-71.11666009999998,"Cambridge, MA 02138, USA","42.3770029,-71.11666009999998"
3,California Institute of Technology (Caltech),http://www.cms.caltech.edu/academics/grad_cms,34.1376576,-118.12526899999999,"1200 E California Blvd, Pasadena, CA 91125, USA","34.1376576,-118.12526899999999"
4,University of Cambridge,https://www.graduate.study.cam.ac.uk/internati...,52.204266600000004,0.1149085,"The Old Schools, Trinity Ln, Cambridge CB2 1TN...","52.204266600000004,0.1149085"

In [8]:
#creating lists to take data from api
name=[]
lat=[]
lng=[]
address=[]
rating=[]

In [33]:
#standard url and api key to use google places api, You need to request search in url format to get data from api,currently we are searching for nearest restaurants.
url="https://maps.googleapis.com/maps/api/place/textsearch/xml?"
api_key="AIzaSyDh4FXrtHWRLS4I2mtnX8X2Hw4TKbkVGu4"
#new="query=Airport&location={}&radius=10000&key={}".format(df.latlong[0],api_key)

In [11]:
for i in df["latlong"]:
    new="query=restaurant&location={}&radius=1000&language=en&key={}".format(i,api_key)
    r=urllib.request.urlopen(url+new)
    soup=BeautifulSoup(r,"lxml")
    name.append(soup.find("name").text)
    lat.append(soup.find("lat").text)
    lng.append(soup.find("lng").text)
    address.append(soup.find("formatted_address").text)

In [18]:
#Now we collected data into empty lists
address

['350 Third St, Cambridge, MA 02142, USA',
 '459 Lagunita Dr, Stanford, CA 94305, USA',
 '52 Brattle St, Cambridge, MA 02138, USA',
 '146 Shoppers Ln, Pasadena, CA 91101, USA',
 '33 Bridge St, Cambridge CB2 1UW, UK',
 '92-94 High St, Oxford OX1 4BJ, UK',
 '16-18 Euston Street, London NW1 1DU, Euston St, London NW1 1DU, United Kingdom',
 '55 Exhibition Rd, Knightsbridge, London SW7 2PN, UK',
 '809 E 63rd St, Chicago, IL 60637, USA',
 'Limmatquai 42, 8001 Zürich, Switzerland',
 '962 Jurong West Street 91, Singapore 640962',
 'Rolex Learning Center, 1015 Ecublens, Switzerland',
 '130 Statler Dr, Ithaca, NY 14853, USA',
 '12 Clementi Rd, Singapore 129742',
 '860 State St, New Haven, CT 06511, USA',
 '301 W 29th St, Baltimore, MD 21211, USA',
 '300 W 114th St, New York, NY 10026, USA',
 '3420 Sansom St, Philadelphia, PA 19104, USA',
 '1/15 Edinburgh Ave, Canberra ACT 2601, Australia',
 '115 W Washington St, Ann Arbor, MI 48104, USA',
 '2608 Erwin Rd # 140, Durham, NC 27705, USA',
 '10-14 Victoria St, Edinburgh EH1 2HG, UK',
 '34-35 Maiden Ln, London WC2E 7LB, UK',
 'Chengfu Rd, WuDaoKou, Haidian Qu, Beijing Shi, China, 100083',
 "No. 3, 5-6, 189, Queen's Rd W, Sai Ying Pun, Hong Kong",
 '2377 Shattuck Ave, Berkeley, CA 94704, USA',
 'Japan, 〒112-0004 Tokyo, Bunkyō, Koraku, 1 Chome−3−61',
 '827 Church St, Evanston, IL 60201, USA',
 'G/F & 1/F, HKUST, Sai Kung, Hong Kong',
 '90 Bloor St E, Toronto, ON M4W 1A7, Canada',
 '1227 Mountain St, Montreal, QC H3G 1Z2, Canada',
 '939 Broxton Ave, Los Angeles, CA 90024, USA',
 '275 Upper Brook St, Manchester M13 0HR, UK',
 '34-35 Maiden Ln, London WC2E 7LB, UK',
 'Japan, 〒606-8395 Kyoto Prefecture, Kyoto, Sakyo Ward, Higashimarutacho, 46-3',
 '1613-4 Bongcheon-dong, Gwanak-gu, Seoul, South Korea',
 '8980 La Jolla Village Dr, La Jolla, CA 92037, United States',
 'Zhongguancun, Haidian, China, 100080',
 'China, Shanghai, Yangpu, 国权后路5号',
 '89-5 Gung-dong, Yuseong-gu, Daejeon, South Korea',
 '209 Lygon St, Carlton VIC 3053, Australia',
 '6 Rue des Fossés Saint-Marcel, 75005 Paris, France',
 '38 College Green, Bristol BS1 5SP, UK',
 '183 Alison Rd, Randwick NSW 2031, Australia',
 'Hong Kong, 沙田香港中文大學范克廉樓',
 '214 N Craig St, Pittsburgh, PA 15213, USA',
 '10/225 Hawken Dr, St Lucia QLD 4067, Australia',
 'Hong Kong, Sham Shui Po, Tai Po Rd, 168-178A號',
 '294 King St, Newtown NSW 2042, Australia',
 '2205 Lower Mall, Vancouver, BC BC V6T, Canada',
 '75 Washington Pl, New York, NY 10011, USA',
 '11 Dorrance St, Providence, RI 02903, USA',
 'Oude Delft 78, 2611 CD Delft, Netherlands',
 '1234 Regent St, Madison, WI 53715, USA',
 'Japan, 〒152-0034 Tokyo, Meguro, Midorigaoka, 1 Chome−14−2',
 '6 University Rd, Coventry CV4 7EZ, UK',
 'Science Park 201, 1098 XH Amsterdam, Netherlands',
 '1 Avenue du Moulin de la Planche, 91120 Palaiseau, France',
 '630 Blackburn Rd, Notting Hill VIC 3168, Australia',
 'Independence, KS 67301, USA',
 'China, Shanghai, Xuhui, 天钥桥路131号永新坊b1楼18号商铺（近辛耕路）',
 '655 Jackson St, San Francisco, CA 94133, USA',
 'Karlspl. 25, 80335 München, Germany',
 '16 Byres Rd, Glasgow G11 5JY, UK',
 'Schönfeldstraße 22, 80539 München, Germany',
 '1610 San Antonio St, Austin, TX 78701, USA',
 'Schurmanstraße 2, 69115 Heidelberg, Germany',
 '710 S Goodwin Ave, Urbana, IL 61801, USA',
 '75 5th St NW, Atlanta, GA 30308, USA',
 "'s-Meiersstraat 3, 3000 Leuven, Belgium",
 '597-2 Yugang-ri, Yeonil-eup, Nam-gu, Pohang, Gyeongsangbuk-do, South Korea',
 'Abel Cathrines Gade 7, 1654 København V, Denmark',
 'Limmatquai 42, 8001 Zürich, Switzerland',
 'AFE, PEDRO DOMINGO MURILLO 725, C1414 CABA, Argentina',
 'No. 3, Lane 265, Section 2, Dunhua South Road, Da’an District, Taipei City, Taiwan 106',
 'Japan, 〒980-0811 Miyagi Prefecture, Sendai, Aoba Ward, Ichibancho, 2−2-11 TKビルディング',
 'The Avenue, Durham DH1 4DX, UK',
 'Scheelevägen 2, 223 63 Lund, Sweden',
 '100 East Franklin Street, 3rd Floor, Chapel Hill, NC 27514, United States',
 '1363 Boylston St, Boston, MA 02215, USA',
 '10 Fitzwilliam St, Sheffield S1 4JB, UK',
 '128 Albert Street, Auckland, 1010, New Zealand',
 '20 Highfield Rd, Birmingham B15 3DU, UK',
 'Redfield Way, Nottingham NG7 2UW, UK',
 '3005 Olentangy River Rd, Columbus, OH 43202, USA',
 'China, Zhejiang, Hangzhou, Xihu, Shihushan Rd, 青芝坞70号',
 'Pembroke Street Upper Pembroke Street Upper, Dublin 2, D02 AK20, Ireland',
 '6400 Fannin Road Suite 218, Houston, TX 77030, United States',
 '2-1 Jong-ro 51ga-gil, Changsin-dong, Jongno-gu, Seoul, South Korea',
 '8629 112 St NW, Edmonton, AB T6G 1K8, Canada',
 'Playfair Terrace, 2 North St, St Andrews KY16 9HX, UK',
 '220 E College Ave, State College, PA 16801, USA',
 '3 Hackett Dr, Crawley WA 6009, Australia',
 'Prospekt Vernadskogo, 6, Moskva, Russia, 119311',
 '165 Temple Street, Jordan, Hong Kong',
 'Huizhou Ave, Baohe Qu, Hefei Shi, Anhui Sheng, China, 230000',
 'Kungstensgatan 2, 114 25 Stockholm, Sweden',
 'Rue Neuve-du-Molard 7, 1204 Genève, Switzerland',
 '6504 Delmar Blvd, St. Louis, MO 63130, USA']

In [19]:
#now we will be attaching these lists to dataframe
df["Nearest Restuarant"]=name
df["lat(Restuarant)"]=lat
df["lng(Restuarant)"]=lng
df["address(Restuarant)"]=address

In [21]:
#Now we have information of nearestest restaurants attached to our spreadsheet.
df.head()

,University name,course Url,Latitude,Longitude,Address,latlong,Nearest Restuarant,lat(Restuarant),lng(Restuarant),address(Restuarant)
0,Massachusetts Institute of Technology (MIT),https://engineering.mit.edu/,42.360091,-71.09416,"77 Massachusetts Ave, Cambridge, MA 02139, USA","42.360091,-71.09416",Za Cambridge,42.3635078,-71.0834699,"350 Third St, Cambridge, MA 02142, USA"
1,Stanford University,https://www.stanford.edu/academics/,37.4274745,-122.169719,"450 Serra Mall, Stanford, CA 94305, USA","37.4274745,-122.169719",Panda Express,37.4245011,-122.1711311,"459 Lagunita Dr, Stanford, CA 94305, USA"
2,Harvard University,https://www.harvard.edu/,42.3770029,-71.11666009999998,"Cambridge, MA 02138, USA","42.3770029,-71.11666009999998",Toscano,42.3743001,-71.1219776,"52 Brattle St, Cambridge, MA 02138, USA"
3,California Institute of Technology (Caltech),http://www.cms.caltech.edu/academics/grad_cms,34.1376576,-118.12526899999999,"1200 E California Blvd, Pasadena, CA 91125, USA","34.1376576,-118.12526899999999",Green Street Restaurant,34.1432300,-118.1311640,"146 Shoppers Ln, Pasadena, CA 91101, USA"
4,University of Cambridge,https://www.graduate.study.cam.ac.uk/internati...,52.204266600000004,0.1149085,"The Old Schools, Trinity Ln, Cambridge CB2 1TN...","52.204266600000004,0.1149085",Galleria Restaurant Cambridge,52.2097410,0.1166410,"33 Bridge St, Cambridge CB2 1UW, UK"

In [22]:
#Now we have to find nearest airports,we have to create empty lists again to collect the data
name=[]
lat=[]
lng=[]
address=[]

In [24]:
#Using same code for finding airports just replacing "query"
for i in df["latlong"]:
    new="query=Airport&location={}&radius=1000&language=en&key={}".format(i,api_key)
    r=urllib.request.urlopen(url+new)
    soup=BeautifulSoup(r,"lxml")
    name.append(soup.find("name").text)
    lat.append(soup.find("lat").text)
    lng.append(soup.find("lng").text)
    address.append(soup.find("formatted_address").text)

In [28]:
#Repeat above procedure to attach dataframe
df["Nearest airport"]=name
df["lat(Airport)"]=lat
df["lng(Airport)"]=lng
df["Address(Airport)"]=address

In [29]:
df.head()

,University name,course Url,Latitude,Longitude,Address,latlong,Nearest Restuarant,lat(Restuarant),lng(Restuarant),address(Restuarant),Nearest airport,lat(Airport),lng(Airport),Address(Airport)
0,Massachusetts Institute of Technology (MIT),https://engineering.mit.edu/,42.360091,-71.09416,"77 Massachusetts Ave, Cambridge, MA 02139, USA","42.360091,-71.09416",Za Cambridge,42.3635078,-71.0834699,"350 Third St, Cambridge, MA 02142, USA",Boston Logan International Airport,42.3656132,-71.0095602,"1 Harborside Dr, Boston, MA 02128, USA"
1,Stanford University,https://www.stanford.edu/academics/,37.4274745,-122.169719,"450 Serra Mall, Stanford, CA 94305, USA","37.4274745,-122.169719",Panda Express,37.4245011,-122.1711311,"459 Lagunita Dr, Stanford, CA 94305, USA",Palo Alto Airport,37.4549654,-122.1107825,"1925 Embarcadero Rd, Palo Alto, CA 94303, USA"
2,Harvard University,https://www.harvard.edu/,42.3770029,-71.11666009999998,"Cambridge, MA 02138, USA","42.3770029,-71.11666009999998",Toscano,42.3743001,-71.1219776,"52 Brattle St, Cambridge, MA 02138, USA",Boston Logan International Airport,42.3656132,-71.0095602,"1 Harborside Dr, Boston, MA 02128, USA"
3,California Institute of Technology (Caltech),http://www.cms.caltech.edu/academics/grad_cms,34.1376576,-118.12526899999999,"1200 E California Blvd, Pasadena, CA 91125, USA","34.1376576,-118.12526899999999",Green Street Restaurant,34.1432300,-118.1311640,"146 Shoppers Ln, Pasadena, CA 91101, USA",El Monte Airport,34.0848443,-118.0330120,"4233 Santa Anita Ave, El Monte, CA 91731, USA"
4,University of Cambridge,https://www.graduate.study.cam.ac.uk/internati...,52.204266600000004,0.1149085,"The Old Schools, Trinity Ln, Cambridge CB2 1TN...","52.204266600000004,0.1149085",Galleria Restaurant Cambridge,52.2097410,0.1166410,"33 Bridge St, Cambridge CB2 1UW, UK",London Stansted Airport,51.8860181,0.2388661,"Bassingbourn Rd, Stansted CM24 1QW, UK"

In [32]:
#Repeat above procedure to find nearest gas station,first we have to clear lists
name.clear()
address.clear()
lat.clear()
lng.clear()

In [34]:
#Using same code for finding airports just replacing "query"
for i in df["latlong"]:
    new="query=GasStation&location={}&radius=1000&language=en&key={}".format(i,api_key)
    r=urllib.request.urlopen(url+new)
    soup=BeautifulSoup(r,"lxml")
    name.append(soup.find("name").text)
    lat.append(soup.find("lat").text)
    lng.append(soup.find("lng").text)
    address.append(soup.find("formatted_address").text)

In [39]:
#attach it to dataframe
df["Nearest Gas station"]=name
df["lat(Gas station)"]=lat
df["lng(Gas Station)"]=lng
df["Address(Gas Station)"]=address

In [41]:
df.to_csv("unicourse.csv",index=False,header=True,encoding="utf-8")